In [1]:
import pandas as pd
import cluj_tools as ct

In [2]:
# I could easily use the boxscores from in the db instead of pulling from ESPN
# but nice that ESPN has them as totals, still could calculate totals for players from boxscores without too much trouble

In [3]:
final_stats_df = ct.player_rater()

In [4]:
# how to properly account for fga and fta in their ranks? Did what I did make sense? doesn't appear to match up well with website
# do I need to remove anyone when I calculate the ranks?

In [6]:
cat_ranks = [#'ast_total_rank','blocks_total_rank','steals_total_rank','reb_total_rank','pts_total_rank','threes_total_rank',
                'ast_avg_rank','blocks_avg_rank','steals_avg_rank','reb_avg_rank','pts_avg_rank','threes_avg_rank',
                'fg_rank_adj','ft_rank_adj']

In [7]:
team = final_stats_df.loc[final_stats_df.onTeamId==10][['playerName']+cat_ranks]
team

,playerName,ast_avg_rank,blocks_avg_rank,steals_avg_rank,reb_avg_rank,pts_avg_rank,threes_avg_rank,fg_rank_adj,ft_rank_adj
223,Giannis Antetokounmpo,2.079846,1.442016,1.142607,3.745141,3.245784,0.658527,2.710353,-4.619297
267,Nikola Jokic,2.664008,0.448381,1.256926,2.542858,1.767044,0.335446,1.406400,0.713829
254,Julius Randle,0.700079,-0.285234,0.452833,2.218755,1.521605,0.097390,0.096187,-0.491935
276,Myles Turner,-0.465609,3.447596,0.198213,0.893110,0.415930,0.516738,0.003370,0.042663
192,Taurean Prince,0.028353,-0.099146,0.741862,1.021651,0.506728,1.621998,-0.692852,-0.051443
46,Derrick Rose,2.108601,-0.295807,0.393714,-0.495178,1.448215,-0.048451,0.748650,0.535406
173,Elfrid Payton,2.642511,0.003766,2.273130,0.319843,0.039828,-0.660433,-0.021398,0.727154
400,Miles Bridges,-0.134018,0.795717,-0.058162,0.711751,0.547733,0.609162,-0.087624,0.076740
123,Justin Holiday,-0.268968,0.537846,0.979014,-0.150476,-0.092973,1.035610,-0.012017,-0.057142
171,Josh Richardson,0.726338,0.448381,0.762860,-0.208154,0.859214,0.670941,-0.105380,0.230680
210,Nerlens Noel,-0.454634,2.587224,1.166443,0.592229,-0.134097,-1.082184,-0.761056,0.046837
184,Maxi Kleber,-0.522674,1.479862,-0.813792,0.627372,0.002002,0.765326,0.037474,-0.134728
327,Matisse Thybulle,-0.421911,1.032887,2.063900,-0.882240,-0.641416,0.029124,0.169028,0.338195
25,Mike Conley,1.160802,-0.682921,0.187114,-0.245366,0.648592,0.909976,-0.174589,0.079789

In [9]:
team[cat_ranks].sum()

ast_avg_rank        9.842724
blocks_avg_rank    10.860569
steals_avg_rank    10.746662
reb_avg_rank       10.691298
pts_avg_rank       10.134189
threes_avg_rank     5.459170
fg_rank_adj         3.316545
ft_rank_adj        -2.563252
dtype: float64

In [10]:
team_stats_list = []
for team_id in range(1, 13):
    team_stats = final_stats_df.loc[(final_stats_df.onTeamId==team_id) & (final_stats_df.injuryStatus!= 'OUT')]
    team_stats = final_stats_df.loc[(final_stats_df.onTeamId==team_id)]
    print(team_stats.shape)
    team_stats_list.append(team_stats[cat_ranks].sum())

(13, 18)
(13, 18)
(13, 18)
(14, 18)
(14, 18)
(11, 18)
(14, 18)
(14, 18)
(14, 18)
(14, 18)
(14, 18)
(14, 18)

In [11]:
team_rater = pd.concat(team_stats_list, axis=1).transpose()
team_ranks = team_rater.rank(ascending=False)
team_rater['teamId'] = list(range(1,13))
team_ranks['teamId'] = list(range(1,13))

In [12]:
# write something to figure out which team is my worst matchup
team_ranks

,ast_avg_rank,blocks_avg_rank,steals_avg_rank,reb_avg_rank,pts_avg_rank,threes_avg_rank,fg_rank_adj,ft_rank_adj,teamId
0,3.0,5.0,2.0,11.0,10.0,11.0,1.0,4.0,1
1,12.0,4.0,11.0,2.0,5.0,7.0,11.0,11.0,2
2,2.0,8.0,8.0,8.0,7.0,10.0,7.0,8.0,3
3,7.0,2.0,12.0,1.0,2.0,5.0,10.0,3.0,4
4,1.0,9.0,4.0,9.0,4.0,1.0,5.0,6.0,5
5,5.0,10.0,6.0,10.0,11.0,3.0,8.0,9.0,6
6,8.0,6.0,9.0,7.0,6.0,4.0,9.0,2.0,7
7,11.0,1.0,1.0,5.0,9.0,9.0,12.0,10.0,8
8,10.0,7.0,7.0,4.0,8.0,8.0,3.0,5.0,9
9,6.0,3.0,3.0,6.0,12.0,12.0,2.0,12.0,10
10,9.0,12.0,10.0,12.0,3.0,6.0,6.0,7.0,11
11,4.0,11.0,5.0,3.0,1.0,2.0,4.0,1.0,12

In [13]:
team_rater

,ast_avg_rank,blocks_avg_rank,steals_avg_rank,reb_avg_rank,pts_avg_rank,threes_avg_rank,fg_rank_adj,ft_rank_adj,teamId
0,12.888048,7.213719,11.818479,7.208904,11.862625,6.010480,4.303909,6.087052,1
1,4.796220,9.700371,6.595854,13.700032,14.087781,8.188526,0.828728,-0.690959,2
2,14.106778,4.740301,9.153625,9.114773,12.672408,6.587306,1.585823,2.869806,3
3,9.727460,11.813808,5.987692,18.198694,18.810353,11.174064,0.987184,7.398512,4
4,17.094879,4.622391,10.381621,8.864366,15.884380,13.865581,2.270163,4.342962,5
5,11.824328,1.242629,9.684761,7.860117,10.447772,12.288539,1.446640,1.206087,6
6,9.138106,6.287666,8.855414,9.353996,13.896151,12.215809,1.046979,9.864330,7
7,6.880415,13.934637,12.705230,12.643936,12.389995,6.627599,0.090965,-0.349259,8
8,7.381724,5.463045,9.454651,12.917407,12.447906,7.036131,3.067726,5.467323,9
9,9.842724,10.860569,10.746662,10.691298,10.134189,5.459170,3.316545,-2.563252,10
10,7.482021,0.539581,8.626973,7.084863,16.011541,10.513214,1.985592,3.830735,11
11,12.291206,1.238694,10.049142,13.368281,20.302678,13.857621,2.821538,11.394348,12