In [79]:
import datetime
import time
import pytz
import pandas as pd

from itertools import chain
from datetime import timedelta, date, datetime, timezone
from basketball_reference_web_scraper import client

from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database

from secrets import *

In [11]:
dbname = 'cluj'
engine = create_engine('postgres://%s:%s@localhost/%s'%('docker','docker',dbname))

if not database_exists(engine.url):
    create_database(engine.url)
print(database_exists(engine.url))

True

In [2]:
#https://stackoverflow.com/questions/1060279/iterating-through-a-range-of-dates-in-python

def daterange(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)

In [ ]:
schedule = client.season_schedule(season_end_year=2020)

In [72]:
start = schedule[0]['start_time']
end = datetime.now(pytz.timezone('US/Central')) - timedelta(days=1)
start, end

(datetime.datetime(2018, 10, 17, 0, 0, tzinfo=<UTC>),
 datetime.datetime(2020, 1, 11, 21, 39, 13, 831959, tzinfo=<DstTzInfo 'US/Central' CST-1 day, 18:00:00 STD>))

In [36]:
schedule_df = pd.DataFrame(schedule)
schedule_df['away_team'] = schedule_df.away_team.apply(lambda x: x.name)
schedule_df['home_team'] = schedule_df.home_team.apply(lambda x: x.name)
schedule_df['start_time'] = schedule_df.start_time.apply(lambda x: x.tz_localize(None))
schedule_df['start_date'] = schedule_df.start_time.apply(lambda x: x.date())
schedule_df['season_end_year'] = 2020
schedule_df.head()

,away_team,away_team_score,home_team,home_team_score,start_time,start_date,season_end_year
0,NEW_ORLEANS_PELICANS,122.0,TORONTO_RAPTORS,130.0,2019-10-23 00:00:00,2019-10-23,2020
1,LOS_ANGELES_LAKERS,102.0,LOS_ANGELES_CLIPPERS,112.0,2019-10-23 02:30:00,2019-10-23,2020
2,CHICAGO_BULLS,125.0,CHARLOTTE_HORNETS,126.0,2019-10-23 23:00:00,2019-10-23,2020
3,DETROIT_PISTONS,119.0,INDIANA_PACERS,110.0,2019-10-23 23:00:00,2019-10-23,2020
4,CLEVELAND_CAVALIERS,85.0,ORLANDO_MAGIC,94.0,2019-10-23 23:00:00,2019-10-23,2020

In [37]:
schedule_df.to_sql('nba_schedule', con=engine, if_exists='replace', index=False)

In [38]:
for year in range(2001, 2020):
    print(year)
    schedule = client.season_schedule(season_end_year=year)
    schedule_df = pd.DataFrame(schedule)
    schedule_df['away_team'] = schedule_df.away_team.apply(lambda x: x.name)
    schedule_df['home_team'] = schedule_df.home_team.apply(lambda x: x.name)
    schedule_df['start_time'] = schedule_df.start_time.apply(lambda x: x.tz_localize(None))
    schedule_df['start_date'] = schedule_df.start_time.apply(lambda x: x.date())
    schedule_df['season_end_year'] = year
    schedule_df.to_sql('nba_schedule', con=engine, if_exists='append', index=False)

2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019

In [87]:
#boxscores_list = []
#for day in daterange(start, end):
#    print(day)
#    boxscores = client.player_box_scores(day=day.day, month=day.month, year=day.year)
#    for item in boxscores:
#        item.update( {"date":datetime.strftime(day.date(), format = '%Y-%m-%d')})
#    boxscores_list.append(boxscores)
#    time.sleep(2)

2018-10-17 00:00:00+00:00
2018-10-18 00:00:00+00:00
2018-10-19 00:00:00+00:00
2018-10-20 00:00:00+00:00
2018-10-21 00:00:00+00:00
2018-10-22 00:00:00+00:00
2018-10-23 00:00:00+00:00
2018-10-24 00:00:00+00:00
2018-10-25 00:00:00+00:00
2018-10-26 00:00:00+00:00
2018-10-27 00:00:00+00:00
2018-10-28 00:00:00+00:00
2018-10-29 00:00:00+00:00
2018-10-30 00:00:00+00:00
2018-10-31 00:00:00+00:00
2018-11-01 00:00:00+00:00
2018-11-02 00:00:00+00:00
2018-11-03 00:00:00+00:00
2018-11-04 00:00:00+00:00
2018-11-05 00:00:00+00:00
2018-11-06 00:00:00+00:00
2018-11-07 00:00:00+00:00
2018-11-08 00:00:00+00:00
2018-11-09 00:00:00+00:00
2018-11-10 00:00:00+00:00
2018-11-11 00:00:00+00:00
2018-11-12 00:00:00+00:00
2018-11-13 00:00:00+00:00
2018-11-14 00:00:00+00:00
2018-11-15 00:00:00+00:00
2018-11-16 00:00:00+00:00
2018-11-17 00:00:00+00:00
2018-11-18 00:00:00+00:00
2018-11-19 00:00:00+00:00
2018-11-20 00:00:00+00:00
2018-11-21 00:00:00+00:00
2018-11-22 00:00:00+00:00
2018-11-23 00:00:00+00:00
2018-11-24 00:00:00+00:00
2018-11-25 00:00:00+00:00
2018-11-26 00:00:00+00:00
2018-11-27 00:00:00+00:00
2018-11-28 00:00:00+00:00
2018-11-29 00:00:00+00:00
2018-11-30 00:00:00+00:00
2018-12-01 00:00:00+00:00
2018-12-02 00:00:00+00:00
2018-12-03 00:00:00+00:00
2018-12-04 00:00:00+00:00
2018-12-05 00:00:00+00:00
2018-12-06 00:00:00+00:00
2018-12-07 00:00:00+00:00
2018-12-08 00:00:00+00:00
2018-12-09 00:00:00+00:00
2018-12-10 00:00:00+00:00
2018-12-11 00:00:00+00:00
2018-12-12 00:00:00+00:00
2018-12-13 00:00:00+00:00
2018-12-14 00:00:00+00:00
2018-12-15 00:00:00+00:00
2018-12-16 00:00:00+00:00
2018-12-17 00:00:00+00:00
2018-12-18 00:00:00+00:00
2018-12-19 00:00:00+00:00
2018-12-20 00:00:00+00:00
2018-12-21 00:00:00+00:00
2018-12-22 00:00:00+00:00
2018-12-23 00:00:00+00:00
2018-12-24 00:00:00+00:00
2018-12-25 00:00:00+00:00
2018-12-26 00:00:00+00:00
2018-12-27 00:00:00+00:00
2018-12-28 00:00:00+00:00
2018-12-29 00:00:00+00:00
2018-12-30 00:00:00+00:00
2018-12-31 00:00:00+00:00
2019-01-01 00:00:00+00:00
2019-01-02 00:00:00+00:00
2019-01-03 00:00:00+00:00
2019-01-04 00:00:00+00:00
2019-01-05 00:00:00+00:00
2019-01-06 00:00:00+00:00
2019-01-07 00:00:00+00:00
2019-01-08 00:00:00+00:00
2019-01-09 00:00:00+00:00
2019-01-10 00:00:00+00:00
2019-01-11 00:00:00+00:00
2019-01-12 00:00:00+00:00
2019-01-13 00:00:00+00:00
2019-01-14 00:00:00+00:00
2019-01-15 00:00:00+00:00
2019-01-16 00:00:00+00:00
2019-01-17 00:00:00+00:00
2019-01-18 00:00:00+00:00
2019-01-19 00:00:00+00:00
2019-01-20 00:00:00+00:00
2019-01-21 00:00:00+00:00
2019-01-22 00:00:00+00:00
2019-01-23 00:00:00+00:00
2019-01-24 00:00:00+00:00
2019-01-25 00:00:00+00:00
2019-01-26 00:00:00+00:00
2019-01-27 00:00:00+00:00
2019-01-28 00:00:00+00:00
2019-01-29 00:00:00+00:00
2019-01-30 00:00:00+00:00
2019-01-31 00:00:00+00:00
2019-02-01 00:00:00+00:00
2019-02-02 00:00:00+00:00
2019-02-03 00:00:00+00:00
2019-02-04 00:00:00+00:00
2019-02-05 00:00:00+00:00
2019-02-06 00:00:00+00:00
2019-02-07 00:00:00+00:00
2019-02-08 00:00:00+00:00
2019-02-09 00:00:00+00:00
2019-02-10 00:00:00+00:00
2019-02-11 00:00:00+00:00
2019-02-12 00:00:00+00:00
2019-02-13 00:00:00+00:00
2019-02-14 00:00:00+00:00
2019-02-15 00:00:00+00:00
2019-02-16 00:00:00+00:00
2019-02-17 00:00:00+00:00
2019-02-18 00:00:00+00:00
2019-02-19 00:00:00+00:00
2019-02-20 00:00:00+00:00
2019-02-21 00:00:00+00:00
2019-02-22 00:00:00+00:00
2019-02-23 00:00:00+00:00
2019-02-24 00:00:00+00:00
2019-02-25 00:00:00+00:00
2019-02-26 00:00:00+00:00
2019-02-27 00:00:00+00:00
2019-02-28 00:00:00+00:00
2019-03-01 00:00:00+00:00
2019-03-02 00:00:00+00:00
2019-03-03 00:00:00+00:00
2019-03-04 00:00:00+00:00
2019-03-05 00:00:00+00:00
2019-03-06 00:00:00+00:00
2019-03-07 00:00:00+00:00
2019-03-08 00:00:00+00:00
2019-03-09 00:00:00+00:00
2019-03-10 00:00:00+00:00
2019-03-11 00:00:00+00:00
2019-03-12 00:00:00+00:00
2019-03-13 00:00:00+00:00
2019-03-14 00:00:00+00:00
2019-03-15 00:00:00+00:00
2019-03-16 00:00:00+00:00
2019-03-17 00:00:00+00:00
2019-03-18 00:00:00+00:00
2019-03-19 00:00:00+00:00
2019-03-20 00:00:00+00:00
2019-03-21 00:00:00+00:00
2019-03-22 00:00:00+00:00
2019-03-23 00:00:00+00:00
2019-03-24 00:00:00+00:00
2019-03-25 00:00:00+00:00
2019-03-26 00:00:00+00:00
2019-03-27 00:00:00+00:00
2019-03-28 00:00:00+00:00
2019-03-29 00:00:00+00:00
2019-03-30 00:00:00+00:00
2019-03-31 00:00:00+00:00
2019-04-01 00:00:00+00:00
2019-04-02 00:00:00+00:00
2019-04-03 00:00:00+00:00
2019-04-04 00:00:00+00:00
2019-04-05 00:00:00+00:00
2019-04-06 00:00:00+00:00
2019-04-07 00:00:00+00:00
2019-04-08 00:00:00+00:00
2019-04-09 00:00:00+00:00
2019-04-10 00:00:00+00:00
2019-04-11 00:00:00+00:00
2019-04-12 00:00:00+00:00
2019-04-13 00:00:00+00:00
2019-04-14 00:00:00+00:00
2019-04-15 00:00:00+00:00
2019-04-16 00:00:00+00:00
2019-04-17 00:00:00+00:00
2019-04-18 00:00:00+00:00
2019-04-19 00:00:00+00:00
2019-04-20 00:00:00+00:00
2019-04-21 00:00:00+00:00
2019-04-22 00:00:00+00:00
2019-04-23 00:00:00+00:00
2019-04-24 00:00:00+00:00
2019-04-25 00:00:00+00:00
2019-04-26 00:00:00+00:00
2019-04-27 00:00:00+00:00
2019-04-28 00:00:00+00:00
2019-04-29 00:00:00+00:00
2019-04-30 00:00:00+00:00
2019-05-01 00:00:00+00:00
2019-05-02 00:00:00+00:00
2019-05-03 00:00:00+00:00
2019-05-04 00:00:00+00:00
2019-05-05 00:00:00+00:00
2019-05-06 00:00:00+00:00
2019-05-07 00:00:00+00:00
2019-05-08 00:00:00+00:00
2019-05-09 00:00:00+00:00
2019-05-10 00:00:00+00:00
2019-05-11 00:00:00+00:00
2019-05-12 00:00:00+00:00
2019-05-13 00:00:00+00:00
2019-05-14 00:00:00+00:00
2019-05-15 00:00:00+00:00
2019-05-16 00:00:00+00:00
2019-05-17 00:00:00+00:00
2019-05-18 00:00:00+00:00
2019-05-19 00:00:00+00:00
2019-05-20 00:00:00+00:00
2019-05-21 00:00:00+00:00
2019-05-22 00:00:00+00:00
2019-05-23 00:00:00+00:00
2019-05-24 00:00:00+00:00
2019-05-25 00:00:00+00:00
2019-05-26 00:00:00+00:00
2019-05-27 00:00:00+00:00
2019-05-28 00:00:00+00:00
2019-05-29 00:00:00+00:00
2019-05-30 00:00:00+00:00
2019-05-31 00:00:00+00:00
2019-06-01 00:00:00+00:00
2019-06-02 00:00:00+00:00
2019-06-03 00:00:00+00:00
2019-06-04 00:00:00+00:00
2019-06-05 00:00:00+00:00
2019-06-06 00:00:00+00:00
2019-06-07 00:00:00+00:00
2019-06-08 00:00:00+00:00
2019-06-09 00:00:00+00:00
2019-06-10 00:00:00+00:00
2019-06-11 00:00:00+00:00
2019-06-12 00:00:00+00:00
2019-06-13 00:00:00+00:00
2019-06-14 00:00:00+00:00
2019-06-15 00:00:00+00:00
2019-06-16 00:00:00+00:00
2019-06-17 00:00:00+00:00
2019-06-18 00:00:00+00:00
2019-06-19 00:00:00+00:00
2019-06-20 00:00:00+00:00
2019-06-21 00:00:00+00:00
2019-06-22 00:00:00+00:00
2019-06-23 00:00:00+00:00
2019-06-24 00:00:00+00:00
2019-06-25 00:00:00+00:00
2019-06-26 00:00:00+00:00
2019-06-27 00:00:00+00:00
2019-06-28 00:00:00+00:00
2019-06-29 00:00:00+00:00
2019-06-30 00:00:00+00:00
2019-07-01 00:00:00+00:00
2019-07-02 00:00:00+00:00
2019-07-03 00:00:00+00:00
2019-07-04 00:00:00+00:00
2019-07-05 00:00:00+00:00
2019-07-06 00:00:00+00:00
2019-07-07 00:00:00+00:00
2019-07-08 00:00:00+00:00
2019-07-09 00:00:00+00:00
2019-07-10 00:00:00+00:00
2019-07-11 00:00:00+00:00
2019-07-12 00:00:00+00:00
2019-07-13 00:00:00+00:00
2019-07-14 00:00:00+00:00
2019-07-15 00:00:00+00:00
2019-07-16 00:00:00+00:00
2019-07-17 00:00:00+00:00
2019-07-18 00:00:00+00:00
2019-07-19 00:00:00+00:00
2019-07-20 00:00:00+00:00
2019-07-21 00:00:00+00:00
2019-07-22 00:00:00+00:00
2019-07-23 00:00:00+00:00
2019-07-24 00:00:00+00:00
2019-07-25 00:00:00+00:00
2019-07-26 00:00:00+00:00
2019-07-27 00:00:00+00:00
2019-07-28 00:00:00+00:00
2019-07-29 00:00:00+00:00
2019-07-30 00:00:00+00:00
2019-07-31 00:00:00+00:00
2019-08-01 00:00:00+00:00
2019-08-02 00:00:00+00:00
2019-08-03 00:00:00+00:00
2019-08-04 00:00:00+00:00
2019-08-05 00:00:00+00:00
2019-08-06 00:00:00+00:00
2019-08-07 00:00:00+00:00
2019-08-08 00:00:00+00:00
2019-08-09 00:00:00+00:00
2019-08-10 00:00:00+00:00
2019-08-11 00:00:00+00:00
2019-08-12 00:00:00+00:00
2019-08-13 00:00:00+00:00
2019-08-14 00:00:00+00:00
2019-08-15 00:00:00+00:00
2019-08-16 00:00:00+00:00
2019-08-17 00:00:00+00:00
2019-08-18 00:00:00+00:00
2019-08-19 00:00:00+00:00
2019-08-20 00:00:00+00:00
2019-08-21 00:00:00+00:00
2019-08-22 00:00:00+00:00
2019-08-23 00:00:00+00:00
2019-08-24 00:00:00+00:00
2019-08-25 00:00:00+00:00
2019-08-26 00:00:00+00:00
2019-08-27 00:00:00+00:00
2019-08-28 00:00:00+00:00

2019-08-29 00:00:00+00:00
2019-08-30 00:00:00+00:00
2019-08-31 00:00:00+00:00
2019-09-01 00:00:00+00:00
2019-09-02 00:00:00+00:00
2019-09-03 00:00:00+00:00
2019-09-04 00:00:00+00:00
2019-09-05 00:00:00+00:00
2019-09-06 00:00:00+00:00
2019-09-07 00:00:00+00:00
2019-09-08 00:00:00+00:00
2019-09-09 00:00:00+00:00
2019-09-10 00:00:00+00:00
2019-09-11 00:00:00+00:00
2019-09-12 00:00:00+00:00
2019-09-13 00:00:00+00:00
2019-09-14 00:00:00+00:00
2019-09-15 00:00:00+00:00
2019-09-16 00:00:00+00:00
2019-09-17 00:00:00+00:00
2019-09-18 00:00:00+00:00
2019-09-19 00:00:00+00:00
2019-09-20 00:00:00+00:00
2019-09-21 00:00:00+00:00
2019-09-22 00:00:00+00:00
2019-09-23 00:00:00+00:00
2019-09-24 00:00:00+00:00
2019-09-25 00:00:00+00:00
2019-09-26 00:00:00+00:00
2019-09-27 00:00:00+00:00
2019-09-28 00:00:00+00:00
2019-09-29 00:00:00+00:00
2019-09-30 00:00:00+00:00
2019-10-01 00:00:00+00:00
2019-10-02 00:00:00+00:00
2019-10-03 00:00:00+00:00
2019-10-04 00:00:00+00:00
2019-10-05 00:00:00+00:00
2019-10-06 00:00:00+00:00
2019-10-07 00:00:00+00:00
2019-10-08 00:00:00+00:00
2019-10-09 00:00:00+00:00
2019-10-10 00:00:00+00:00
2019-10-11 00:00:00+00:00
2019-10-12 00:00:00+00:00
2019-10-13 00:00:00+00:00
2019-10-14 00:00:00+00:00
2019-10-15 00:00:00+00:00
2019-10-16 00:00:00+00:00
2019-10-17 00:00:00+00:00
2019-10-18 00:00:00+00:00
2019-10-19 00:00:00+00:00
2019-10-20 00:00:00+00:00
2019-10-21 00:00:00+00:00
2019-10-22 00:00:00+00:00
2019-10-23 00:00:00+00:00
2019-10-24 00:00:00+00:00
2019-10-25 00:00:00+00:00
2019-10-26 00:00:00+00:00
2019-10-27 00:00:00+00:00
2019-10-28 00:00:00+00:00
2019-10-29 00:00:00+00:00
2019-10-30 00:00:00+00:00
2019-10-31 00:00:00+00:00
2019-11-01 00:00:00+00:00
2019-11-02 00:00:00+00:00
2019-11-03 00:00:00+00:00
2019-11-04 00:00:00+00:00
2019-11-05 00:00:00+00:00
2019-11-06 00:00:00+00:00
2019-11-07 00:00:00+00:00
2019-11-08 00:00:00+00:00
2019-11-09 00:00:00+00:00
2019-11-10 00:00:00+00:00
2019-11-11 00:00:00+00:00
2019-11-12 00:00:00+00:00
2019-11-13 00:00:00+00:00
2019-11-14 00:00:00+00:00
2019-11-15 00:00:00+00:00
2019-11-16 00:00:00+00:00
2019-11-17 00:00:00+00:00
2019-11-18 00:00:00+00:00
2019-11-19 00:00:00+00:00
2019-11-20 00:00:00+00:00
2019-11-21 00:00:00+00:00
2019-11-22 00:00:00+00:00
2019-11-23 00:00:00+00:00
2019-11-24 00:00:00+00:00
2019-11-25 00:00:00+00:00
2019-11-26 00:00:00+00:00
2019-11-27 00:00:00+00:00
2019-11-28 00:00:00+00:00
2019-11-29 00:00:00+00:00
2019-11-30 00:00:00+00:00
2019-12-01 00:00:00+00:00
2019-12-02 00:00:00+00:00
2019-12-03 00:00:00+00:00
2019-12-04 00:00:00+00:00
2019-12-05 00:00:00+00:00
2019-12-06 00:00:00+00:00
2019-12-07 00:00:00+00:00
2019-12-08 00:00:00+00:00
2019-12-09 00:00:00+00:00
2019-12-10 00:00:00+00:00
2019-12-11 00:00:00+00:00
2019-12-12 00:00:00+00:00
2019-12-13 00:00:00+00:00
2019-12-14 00:00:00+00:00
2019-12-15 00:00:00+00:00
2019-12-16 00:00:00+00:00
2019-12-17 00:00:00+00:00
2019-12-18 00:00:00+00:00
2019-12-19 00:00:00+00:00
2019-12-20 00:00:00+00:00
2019-12-21 00:00:00+00:00
2019-12-22 00:00:00+00:00
2019-12-23 00:00:00+00:00
2019-12-24 00:00:00+00:00
2019-12-25 00:00:00+00:00
2019-12-26 00:00:00+00:00
2019-12-27 00:00:00+00:00
2019-12-28 00:00:00+00:00
2019-12-29 00:00:00+00:00
2019-12-30 00:00:00+00:00
2019-12-31 00:00:00+00:00
2020-01-01 00:00:00+00:00
2020-01-02 00:00:00+00:00
2020-01-03 00:00:00+00:00
2020-01-04 00:00:00+00:00
2020-01-05 00:00:00+00:00
2020-01-06 00:00:00+00:00
2020-01-07 00:00:00+00:00
2020-01-08 00:00:00+00:00
2020-01-09 00:00:00+00:00
2020-01-10 00:00:00+00:00
2020-01-11 00:00:00+00:00

In [63]:
date = datetime.now() - timedelta(days=1)
print(date)
boxscores = client.player_box_scores(day=date.day, month=date.month, year=date.year)

2020-01-11 21:35:14.469029

In [88]:
#boxscores_df = pd.DataFrame(list(chain.from_iterable(boxscores_list)))
boxscores_df = pd.DataFrame(boxscores)
boxscores_df['rebounds'] = boxscores_df.offensive_rebounds + boxscores_df.defensive_rebounds
boxscores_df.rename(columns={'attempted_field_goals':'fga', 'attempted_free_throws':'fta',
                            'made_three_point_field_goals':'threes', 'made_field_goals':'fgm',
                            'made_free_throws':'ftm'}, inplace=True)
boxscores_df['twos'] = boxscores_df.fgm - boxscores_df.threes
boxscores_df['points'] = (boxscores_df.threes * 3) + (boxscores_df.twos * 2) + (boxscores_df.ftm * 1)
boxscores_df.drop(columns=['attempted_three_point_field_goals','defensive_rebounds','offensive_rebounds',
                          'game_score','slug','turnovers','outcome','twos','personal_fouls','location'], inplace=True)
boxscores_df['opponent'] = boxscores_df.opponent.apply(lambda x: x.name)
boxscores_df['team'] = boxscores_df.team.apply(lambda x: x.name)
boxscores_df.columns.values

array(['assists', 'fga', 'fta', 'blocks', 'date', 'fgm', 'ftm', 'threes',
       'name', 'opponent', 'seconds_played', 'steals', 'team', 'rebounds',
       'points'], dtype=object)

In [89]:
boxscores_df.shape

(40204, 15)

In [92]:
boxscores_df.to_sql('boxscores', con=engine, if_exists='append', index=False)

In [57]:
boxscores_df.loc[boxscores_df.name.str.contains("Satorans")]

,assists,fga,fta,blocks,fgm,ftm,threes,name,opponent,seconds_played,steals,team,rebounds,points
181,3,5,0,1,1,0,0,Tomáš Satoranský,CHARLOTTE_HORNETS,1462,0,CHICAGO_BULLS,0,2
349,2,7,5,1,2,5,0,Tomáš Satoranský,MEMPHIS_GRIZZLIES,1317,4,CHICAGO_BULLS,3,9
602,4,7,0,0,3,0,2,Tomáš Satoranský,TORONTO_RAPTORS,1578,1,CHICAGO_BULLS,2,8
994,5,5,0,0,1,0,0,Tomáš Satoranský,NEW_YORK_KNICKS,1608,1,CHICAGO_BULLS,3,2
1224,8,5,2,0,2,2,2,Tomáš Satoranský,CLEVELAND_CAVALIERS,1635,0,CHICAGO_BULLS,2,8
1550,6,6,2,0,2,2,1,Tomáš Satoranský,DETROIT_PISTONS,1587,0,CHICAGO_BULLS,0,7
1801,9,6,0,0,4,0,1,Tomáš Satoranský,INDIANA_PACERS,1619,2,CHICAGO_BULLS,4,9
2066,6,5,0,0,3,0,1,Tomáš Satoranský,LOS_ANGELES_LAKERS,1594,1,CHICAGO_BULLS,4,7
2157,8,13,4,0,10,3,4,Tomáš Satoranský,ATLANTA_HAWKS,1800,1,CHICAGO_BULLS,7,27
2731,4,11,3,0,4,2,0,Tomáš Satoranský,HOUSTON_ROCKETS,1438,3,CHICAGO_BULLS,3,10
3196,2,3,0,0,2,0,1,Tomáš Satoranský,NEW_YORK_KNICKS,1401,0,CHICAGO_BULLS,2,5
3428,5,8,0,0,4,0,2,Tomáš Satoranský,MILWAUKEE_BUCKS,1645,3,CHICAGO_BULLS,4,10
3775,2,8,0,0,2,0,1,Tomáš Satoranský,BROOKLYN_NETS,1712,3,CHICAGO_BULLS,8,5
4139,1,6,0,0,2,0,1,Tomáš Satoranský,MILWAUKEE_BUCKS,1073,0,CHICAGO_BULLS,1,5
4287,7,11,0,0,6,0,3,Tomáš Satoranský,DETROIT_PISTONS,1571,2,CHICAGO_BULLS,4,15
4638,5,5,2,0,2,2,0,Tomáš Satoranský,MIAMI_HEAT,1260,2,CHICAGO_BULLS,2,6
4764,8,8,0,1,4,0,2,Tomáš Satoranský,CHARLOTTE_HORNETS,1653,3,CHICAGO_BULLS,3,10
5169,5,12,0,0,5,0,1,Tomáš Satoranský,PORTLAND_TRAIL_BLAZERS,1629,0,CHICAGO_BULLS,5,11
5341,7,12,3,0,7,2,3,Tomáš Satoranský,GOLDEN_STATE_WARRIORS,2102,2,CHICAGO_BULLS,7,19
5667,8,8,2,0,4,2,2,Tomáš Satoranský,PORTLAND_TRAIL_BLAZERS,1790,1,CHICAGO_BULLS,3,12
6206,5,9,8,0,3,8,0,Tomáš Satoranský,SACRAMENTO_KINGS,2015,1,CHICAGO_BULLS,2,14
6482,8,10,9,0,3,7,0,Tomáš Satoranský,MEMPHIS_GRIZZLIES,1994,3,CHICAGO_BULLS,6,13
6871,5,7,0,0,3,0,0,Tomáš Satoranský,GOLDEN_STATE_WARRIORS,1939,2,CHICAGO_BULLS,2,6
7177,2,8,2,0,2,2,0,Tomáš Satoranský,MIAMI_HEAT,1363,0,CHICAGO_BULLS,3,6
7266,11,8,0,0,4,0,2,Tomáš Satoranský,TORONTO_RAPTORS,2279,2,CHICAGO_BULLS,3,10
7642,4,5,0,0,3,0,1,Tomáš Satoranský,ATLANTA_HAWKS,1438,1,CHICAGO_BULLS,2,7
7968,3,8,4,0,2,3,0,Tomáš Satoranský,CHARLOTTE_HORNETS,1544,0,CHICAGO_BULLS,3,7
8094,5,7,4,1,2,3,0,Tomáš Satoranský,LOS_ANGELES_CLIPPERS,1674,2,CHICAGO_BULLS,3,7
8338,6,9,2,1,4,2,1,Tomáš Satoranský,OKLAHOMA_CITY_THUNDER,1980,3,CHICAGO_BULLS,6,11
8600,6,11,1,0,7,1,2,Tomáš Satoranský,WASHINGTON_WIZARDS,2065,1,CHICAGO_BULLS,7,17
9093,5,11,2,0,6,2,2,Tomáš Satoranský,DETROIT_PISTONS,2289,2,CHICAGO_BULLS,8,16
9383,3,12,0,0,8,0,4,Tomáš Satoranský,ORLANDO_MAGIC,2002,1,CHICAGO_BULLS,6,20
9996,6,8,1,0,5,0,1,Tomáš Satoranský,ATLANTA_HAWKS,1798,3,CHICAGO_BULLS,8,11
10424,7,11,0,0,4,0,2,Tomáš Satoranský,MILWAUKEE_BUCKS,1552,0,CHICAGO_BULLS,2,10
10809,4,7,2,0,3,2,0,Tomáš Satoranský,UTAH_JAZZ,2044,2,CHICAGO_BULLS,0,8
11125,5,11,3,0,4,3,1,Tomáš Satoranský,BOSTON_CELTICS,2389,1,CHICAGO_BULLS,6,12
11417,14,12,4,0,3,4,1,Tomáš Satoranský,DALLAS_MAVERICKS,2090,1,CHICAGO_BULLS,5,11
11861,1,6,2,0,2,1,1,Tomáš Satoranský,NEW_ORLEANS_PELICANS,1520,0,CHICAGO_BULLS,4,6
12061,3,11,2,1,5,2,1,Tomáš Satoranský,INDIANA_PACERS,2233,1,CHICAGO_BULLS,3,13